// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf_fdCKGbn4DN4KEHyahGIy56DwuHbIsU',
    appId: '1:864747415342:web:ab5c87162ead50eff73cbf',
    messagingSenderId: '864747415342',
    projectId: 'cryptocalculator-b7647',
    authDomain: 'cryptocalculator-b7647.firebaseapp.com',
    storageBucket: 'cryptocalculator-b7647.firebasestorage.app',
    measurementId: 'G-48CNXZQN7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyiJ9rJOL6tWl_t8wW3cXiOirk6CMpZQE',
    appId: '1:864747415342:android:ac8e4a0b5bf554c6f73cbf',
    messagingSenderId: '864747415342',
    projectId: 'cryptocalculator-b7647',
    storageBucket: 'cryptocalculator-b7647.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz3ukekeufLfrSiHb41bn23dFdl0F_Pyo',
    appId: '1:864747415342:ios:cddb702cb364e288f73cbf',
    messagingSenderId: '864747415342',
    projectId: 'cryptocalculator-b7647',
    storageBucket: 'cryptocalculator-b7647.firebasestorage.app',
    iosBundleId: 'com.example.cryptoCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz3ukekeufLfrSiHb41bn23dFdl0F_Pyo',
    appId: '1:864747415342:ios:cddb702cb364e288f73cbf',
    messagingSenderId: '864747415342',
    projectId: 'cryptocalculator-b7647',
    storageBucket: 'cryptocalculator-b7647.firebasestorage.app',
    iosBundleId: 'com.example.cryptoCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf_fdCKGbn4DN4KEHyahGIy56DwuHbIsU',
    appId: '1:864747415342:web:a31885c03484e455f73cbf',
    messagingSenderId: '864747415342',
    projectId: 'cryptocalculator-b7647',
    authDomain: 'cryptocalculator-b7647.firebaseapp.com',
    storageBucket: 'cryptocalculator-b7647.firebasestorage.app',
    measurementId: 'G-913HV9EQB7',
  );
}
